USE [master]
GO
/****** Object:  Database [DataBaseName]    Script Date: 2/4/2021 7:53:11 AM ******/
CREATE DATABASE [DataBaseName]
GO
ALTER DATABASE [DataBaseName] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataBaseName].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DataBaseName] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [DataBaseName] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DataBaseName] SET ANSI_PADDING ON 
GO
ALTER DATABASE [DataBaseName] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DataBaseName] SET ARITHABORT ON 
GO
ALTER DATABASE [DataBaseName] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DataBaseName] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DataBaseName] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DataBaseName] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DataBaseName] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [DataBaseName] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [DataBaseName] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DataBaseName] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [DataBaseName] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DataBaseName] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DataBaseName] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DataBaseName] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DataBaseName] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DataBaseName] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DataBaseName] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DataBaseName] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DataBaseName] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DataBaseName] SET RECOVERY FULL 
GO
ALTER DATABASE [DataBaseName] SET  MULTI_USER 
GO
ALTER DATABASE [DataBaseName] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DataBaseName] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DataBaseName] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DataBaseName] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DataBaseName] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DataBaseName] SET QUERY_STORE = OFF
GO
USE [DataBaseName]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [DataBaseName]
GO
/****** Object:  Table [dbo].[OrderItems]    Script Date: 2/4/2021 7:53:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SparePartId] [int] NOT NULL,
	[OrderId] [int] NOT NULL,
	[Count] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 2/4/2021 7:53:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VehicleId] [int] NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SpareParts]    Script Date: 2/4/2021 7:53:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SpareParts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vehicles]    Script Date: 2/4/2021 7:53:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vehicles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VehicleTypeId] [int] NOT NULL,
	[ModelName] [nvarchar](50) NOT NULL,
	[RegistrationNumber] [nvarchar](10) NOT NULL,
	[Weight] [int] NOT NULL,
	[ManufactureYear] [int] NOT NULL,
	[Mileage] [int] NOT NULL,
	[Color] [nvarchar](10) NOT NULL,
	[VolumeOfTank] [float] NOT NULL,
	[Consumption] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VehicleTypes]    Script Date: 2/4/2021 7:53:11 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VehicleTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TypeName] [nvarchar](50) NOT NULL,
	[TaxCoefficient] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD FOREIGN KEY([OrderId])
REFERENCES [dbo].[Orders] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD FOREIGN KEY([SparePartId])
REFERENCES [dbo].[SpareParts] ([Id])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([VehicleId])
REFERENCES [dbo].[Vehicles] ([Id])
GO
ALTER TABLE [dbo].[Vehicles]  WITH CHECK ADD FOREIGN KEY([VehicleTypeId])
REFERENCES [dbo].[VehicleTypes] ([Id])
GO
USE [master]
GO
ALTER DATABASE [DataBaseName] SET  READ_WRITE 
GO
